services:
  - type: web
    name: weather-app
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: weather-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: weather-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: weather-db
          property: password
    buildCommand: ./mvnw clean install
    startCommand: java -jar app.jar
    autoDeploy: true
    healthCheckPath: /

databases:
  - name: weather-db
    plan: free
    postgresVersion: 13
    databaseName: weather_service
    user: postgres
    password: O1234