services:
  - type: web
    name: weather-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:${{ fromDatabase.weather-db.connectionString }}
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: weather-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: weather-db
          property: password
databases:
  - name: weather-db
    plan: free
    databaseName: weather_service